### ISSUE TITLE
Como resolver YIELDS sincronos aninhados?

### ISSUE THREAD

**Issue by PauloLuan** [sjcdigital/sjc-digital-cli#4]
A linha 76 [do arquivo index da pasta bus](https://github.com/sjcdigital/sjc-digital-cli/blob/master/lib/bus/index.js#L76) faz um Yield pra pegar o resultado da função `parseBusPage` da [linha 84](https://github.com/sjcdigital/sjc-digital-cli/blob/master/lib/bus/index.js#L84).

No entando, a linha 84 tem outro Yield com o mesmo objetivo de pegar o resultado da próxima função de maneira asyncrona de forma a retornar o resultado para a função `parseBuses`.

A dúvida é, como faço pro resultado da segunda função ser 'sincrono via generator' se o primeiro YIELD vai ser disparado quando eu chamar um Yield na segunda função? 

O problema é que ao invés de retornar a última linha da função com o resultado dos processamentos, ele retorna o resultado do primeiro Yield (o resultado do [get da função getPage](https://github.com/sjcdigital/sjc-digital-cli/blob/master/lib/bus/index.js#L84))

ps: sei que vou ter que mudar o return da função [parseBusPage](https://github.com/sjcdigital/sjc-digital-cli/blob/master/lib/bus/index.js#L87) mas isso ainda não faz diferença no problema descrito.

**Comment by PauloLuan** [comment]
@rafaeljesus e/ou @suissa, mestres do Javascript. O que devo fazer nessa bagaça ?

**Comment by PauloLuan** [comment]
ps: Feedback em relação a melhorias na qualidade do código sao bem vindas sou /n00b em ES6

**Comment by rafaeljesus** [comment]
@PauloLuan firstly you want to wrap proto function with generators like so:

```javascript
BusCrawler.prototype.parseBusPage = co.wrap(function * (bus) {
})
```

Honestly I think we need a full refactoring here 😛  I see all the proto functions being public which in case they should not, so it leads me to think the are being consumed. Also we need to cover it with tests asap so we can do safe refactoring's let me dive into the code to see more
